# 应用名称
spring:
  application:
    name: buyi
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/buyi?serverTimezone=GMT%2B8&useSSL=true
    username: root
    password: root
server:
  port: 8080
mybatis:
  mapper-locations: classpath:mapper/*.xml